Fix build error. Point to correct header location
Fixes: "./drivers/usb/gadget/function/f_gsi.c:21:19: fatal error: debug.h: No such file or directory"
(cherry picked from commit da3887edf6897fac409acd73ef3223b5007f8ac0)